### PR TITLE
[dynamic_color] Impl. [isCorePaletteSupported] API #390

### LINKED ISSUE #390: dynamic_color: Add a method to check whether the platform supports dynamic theming
### Package

dynamic_color

### Description

**Is your feature request related to a problem? Please describe.**
I have dynamic theming as an option in my app. I would only like to show this option when dynamic themes are truly supported.

**Describe the solution you'd like**
Add a "supportedByPlatform" method or something along those lines, to check whether dynamic theming is supported by the platform.

**Describe alternatives you've considered**
I can write the logic myself, but then I'd have to integrate an extra plug-in just for this use case and would have to manually update that logic each and every time more platform support was added to dynamic_color.

### PR DESCRIPTION
**Pull request by alexrintt**
## Description

I did need a built-in method to verify if [getCorePalette] is supported by the host platform without third-party solutions such as [pub.dev/available](https://pub.dev/packages/available) or [pub.dev/device_info_plus](https://pub.dev/packages/device_info_plus), 
 see also #390.

Note: this PR includes only the [isCorePaletteSupported] API, I'll try to send another PR to implement [isAccentColorPaletteSupported] also, if/when it gets approved.

## Tests

- Added test cases to check whether or not the method is handling `null`, `false` and `true` values coming from the host platform using the same way it's currently implemented for the other APIs.

## Issues

Partially fixes #390 since this PR is missing the [isAccentColorPaletteSupported] which is just the same check as I did in this PR but for the desktop platforms.

## Checklist

- [x] I've reviewed the [contribution guide](https://github.com/material-foundation/flutter-packages/blob/main/CONTRIBUTING.md).
- [x] I've updated the package `CHANGELOG.md`

### CODE REVIEW

**Comment by guidezpl** [comment]
Thanks for this. However I think it would be preferable to add this check as a short-circuit exit to the existing API (`getCorePalette`), rather than to add a new method. LMK if you'd like to do this

**Review by guidezpl — CHANGES_REQUESTED** [review]
Thanks for this. However I think it would be preferable to add this check as a short-circuit exit to the existing API (`getCorePalette`), rather than to add a new method. LMK if you'd like to do this

**Comment by alexrintt** [comment]
Sure, since we are going to return null when the dynamic color features aren't available this PR doesn't make sense because the plugin is already [returning null when the SDK Int is below `S`](https://github.com/material-foundation/flutter-packages/blob/3019501d64747a01df341a488ebb845f714b33a8/packages/dynamic_color/android/src/main/kotlin/io/material/plugins/dynamic_color/DynamicColorPlugin.kt#L39).

---

Since for Android there are more checks to do in order to determine if this API is available or not, I am planning to open another PR to add these checks in this plugin. The checklist for the additional checks is as follows:

- [x] Complete SDK Int check (already implemented).
- [ ] Add [BuildCompat.isAtLeastT() check](https://github.com/material-components/material-components-android/blob/392acf98c36041b381455e2889477e136a5a19f0/lib/java/com/google/android/material/color/DynamicColors.java#L404).
- [ ] Add [Manufacturer check](https://github.com/material-components/material-components-android/blob/392acf98c36041b381455e2889477e136a5a19f0/lib/java/com/google/android/material/color/DynamicColors.java#L407C5-L408C96).
- [ ] Add [brand check fallback](https://github.com/material-components/material-components-android/blob/392acf98c36041b381455e2889477e136a5a19f0/lib/java/com/google/android/material/color/DynamicColors.java#L410C1-L411C84).
- [ ] Verify the result of [`com.google.android.material.color.DynamicColors#isDynamicColorAvailable`](https://github.com/material-components/material-components-android/blob/392acf98c36041b381455e2889477e136a5a19f0/lib/java/com/google/android/material/color/DynamicColors.java#L413C1-L413C83) to ensure it returns true.

If any check fails, I will also return null. Does that sound reasonable?

**Comment by guidezpl** [comment]
Sounds reasonable!

**Pull request closed without merging**
