### PR TITLE
[dynamic_color] Add new colors

### LINKED ISSUE #582: Package `dynamic_color` does not initialize new `ColorScheme` roles
### Package

dynamic_color

### Existing issue?

- [X] I checked the [existing issues](https://github.com/material-foundation/flutter-packages/issues)

## Steps to reproduce:
1. Switch to the beta channel and upgrade Flutter using:
```
flutter channel beta
```
and then:
```
flutter upgrade
```
2. Create a new Flutter app.
3. Add the `dynamic_color` package:
```
flutter pub add dynamic_color
```
4.  Use a platform where `DynamicColorPlugin.getCorePalette` does not return `null` (like Android).
5. Use the `DynamicColorBuilder` widget and view its generated `ColorScheme` properties, especially the new color roles like `primaryFixed` `surfaceContainer` and so on. (done using `Text` widgets in the code sample below).

### Code Sample
The following code uses `DynamicColorBuilder` and displays some of the generated colors using `Text` widgets.
```dart
import 'package:dynamic_color/dynamic_color.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  @override
  Widget build(BuildContext context) {
    return DynamicColorBuilder(
      builder: (light, dark) => MaterialApp(
        title: 'Flutter Demo',
        theme: ThemeData(
          colorScheme: light,
          useMaterial3: true,
        ),
        themeMode: ThemeMode.system,
        home: const MyHomePage(title: 'DynamicColorBuilder Demo'),
        )
      );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});  
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {

  @override
  Widget build(BuildContext context) {
    final light = Theme.of(context).colorScheme;

    return Scaffold(
      backgroundColor: Theme.of(context).colorScheme.surfaceContainerLowest,
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
              children: [
                Text('Primary ${light.primary}'),
                Text('Primary Fixed ${light.primaryFixed} ${light.primaryFixed == light.primary}'),
                Text('Primary Fixed Dim  ${light.primaryFixedDim} ${light.primaryFixedDim == light.primary}'),
                Text('Surface  ${light.surface}'),
                Text('Surface Container  ${light.surfaceContainer} ${light.surfaceContainer == light.surface}'),
              ],),
            ), 
    );
  }
}


```
## Expected Results
Extension method `CorePaletteToColorScheme.toColorScheme()` should assign each of these new surface and fixed color roles. 

## Actual results
All the new color roles return the fallback colors. For instance, `primaryFixed` and `primaryFixedDim` return the fallback `primary` because this is the behavior of Flutter's `ColorScheme` as can be seen in its source:
```dart
 final Color? _primaryFixed;
  /// A substitute for [primaryContainer] that's the same color for the dark
  /// and light themes.
  Color get primaryFixed => _primaryFixed ?? primary;

  final Color? _primaryFixedDim;
  /// A color used for elements needing more emphasis than [primaryFixed].
  Color get primaryFixedDim => _primaryFixedDim ?? primary;
```

## Reason
This is happening because `DynamicColorBuilder`  converts a `CorePalette` to a Flutter `ColorScheme` using the extension method on `CorePalette`: `CorePaletteToColorScheme.toColorScheme()`. This method still uses the deprecated `Scheme.lightFromCorePalette` and `Scheme.darkFromCorePalette` methods and does not assign colors to the new roles. 

I tried to manually write my own builder using the `DynamicColorPlugin.getCorePalette` method. However, the MCU library does mention an explicit way to convert a `CorePalette` to the new `DynamicScheme` type (so I created an issue [here](https://github.com/material-foundation/material-color-utilities/issues/148).
 

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by MahanRahmati**
## Description
Add new material colors introduced in Flutter 3.22.

## Issues
Fixes #582 

## Checklist

- [x] I've reviewed the [contribution guide](https://github.com/material-foundation/flutter-packages/blob/main/CONTRIBUTING.md).
- [x] I've updated the package `CHANGELOG.md`

### CODE REVIEW

**Comment by MahanRahmati** [comment]
We need to bump material_color_utilities, and it is an SDK dependency.

**Comment by boredcodebyk** [comment]
new colors doesn't seem to be added in `Scheme` and they apparently moved to `DynamicScheme` as `Scheme` is deprecated (see [this](https://github.com/material-foundation/material-color-utilities/blob/c0930827c66e8855868e2bbac6edfa9ca96e15f6/dart/lib/scheme/scheme.dart#L21))

this package seem to direct take `CorePalette` from android. I tried to make following changes locally according to their [migration guide](https://github.com/material-foundation/material-color-utilities/blob/main/make_schemes.md)

```
final SchemeTonalSpot scheme;
    
    switch (brightness) {
      case Brightness.light:
        scheme = SchemeTonalSpot(
            sourceColorHct: Hct.fromInt(primary.keyColor.toInt()),
            isDark: false,
            contrastLevel: 0.0);
        break;
      case Brightness.dark:
        scheme = SchemeTonalSpot(
            sourceColorHct: Hct.fromInt(primary.keyColor.toInt()),
            isDark: true,
            contrastLevel: 0.0);
        break;
    }
...
return ColorScheme(
      primary: Color(MaterialDynamicColors.primary.getArgb(scheme)),
      onPrimary: Color(MaterialDynamicColors.onPrimary.getArgb(scheme)),
...
```

but the unit test fails
```
dynamic_color: Core palette detected.
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following TestFailure was thrown running a test:
Expected: Color:<Color(0xff286c2a)>
  Actual: Color:<Color(0xff8c4a60)>
```

for reference I used code from `ColorScheme.fromSeed()` from Flutter SDK

**Comment by andr202** [comment]
@boredcodebyk 

> but the unit test fails
> 
> ```
> dynamic_color: Core palette detected.
> ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
> The following TestFailure was thrown running a test:
> Expected: Color:<Color(0xff286c2a)>
>   Actual: Color:<Color(0xff8c4a60)>
> ```
> 
> for reference I used code from `ColorScheme.fromSeed()` from Flutter SDK


Shouldn't just correcting expecting colors in test file enough if everything else works perfectly? (not based on this error but checking what's the real output of given colorscheme in test on md3 colorscheme generator, as colorscheme colors changed, now we need to change test file too)

**Comment by boredcodebyk** [comment]
@andr202 
you have a valid point 
but theoretical the test doesn't needs to be changed. in the test file a container is given primary color and tested with the expected color which passes. in this case, the primary color gets way off from expected color for some reason. I'm still looking into it

**Comment by resucutie** [comment]
Is there still any goals to be met with this PR? The merge request is very waited due to the changes on 3.22

**Comment by hasali19** [comment]
Hi @MahanRahmati, how do I use this branch? It seems to fail as the new properties do not exist in the Scheme class in material_color_utilities.
https://github.com/material-foundation/material-color-utilities/blob/main/dart/lib/scheme/scheme.dart

**Comment by MahanRahmati** [comment]
> Hi @MahanRahmati, how do I use this branch? It seems to fail as the new properties do not exist in the Scheme class in material_color_utilities. https://github.com/material-foundation/material-color-utilities/blob/main/dart/lib/scheme/scheme.dart

You can't use it yet. 
The branch is broken.
I'm waiting for flutter to bump material_color_utilities and update the branch later.

**Comment by Henry-Hiles** [comment]
This is quite urgent, has flutter bumped that yet?

**Comment by guidezpl** [comment]
FYI https://github.com/flutter/flutter/blob/main/packages/flutter/pubspec.yaml#L15 is bumped

**Comment by guidezpl** [comment]
Closing as the approach here will necessitate something like https://github.com/material-foundation/flutter-packages/compare/main...hasali19:material-foundation-flutter-packages:main (with fixes as the color mappings aren't accurate) to construct the color scheme

**Pull request closed without merging**
